apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nginx-argo-service
  description: Nginx deployment managed via ArgoCD
  annotations:
    # CRITICAL: This must match the Application name in ArgoCD
    argocd/app-name: 'nginx-deployment' 
    # Link to the GitHub source
    github.com/project-slug: sreekanth-ragi/k8s-argo
    # Optional: Link to Kubernetes runtime info
    backstage.io/kubernetes-id: nginx-k8s-id
spec:
  type: service
  lifecycle: production
  owner: group:default/frontend-admin
