apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  backstage.io/kubernetes-id: nginx-k8s-id
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        backstage.io/kubernetes-id: nginx-k8s-id
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
